/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as JillesRouteImport } from './routes/jilles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiSlugIndexRouteImport } from './routes/wiki.$slug.index'
import { Route as WikiSlugHistoryRouteImport } from './routes/wiki.$slug.history'
import { Route as WikiSlugEditRouteImport } from './routes/wiki.$slug.edit'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JillesRoute = JillesRouteImport.update({
  id: '/jilles',
  path: '/jilles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugIndexRoute = WikiSlugIndexRouteImport.update({
  id: '/wiki/$slug/',
  path: '/wiki/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugHistoryRoute = WikiSlugHistoryRouteImport.update({
  id: '/wiki/$slug/history',
  path: '/wiki/$slug/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugEditRoute = WikiSlugEditRouteImport.update({
  id: '/wiki/$slug/edit',
  path: '/wiki/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/jilles': typeof JillesRoute
  '/new': typeof NewRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/jilles': typeof JillesRoute
  '/new': typeof NewRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug': typeof WikiSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/jilles': typeof JillesRoute
  '/new': typeof NewRoute
  '/wiki/$slug/edit': typeof WikiSlugEditRoute
  '/wiki/$slug/history': typeof WikiSlugHistoryRoute
  '/wiki/$slug/': typeof WikiSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/jilles'
    | '/new'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/jilles'
    | '/new'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/jilles'
    | '/new'
    | '/wiki/$slug/edit'
    | '/wiki/$slug/history'
    | '/wiki/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JillesRoute: typeof JillesRoute
  NewRoute: typeof NewRoute
  WikiSlugEditRoute: typeof WikiSlugEditRoute
  WikiSlugHistoryRoute: typeof WikiSlugHistoryRoute
  WikiSlugIndexRoute: typeof WikiSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jilles': {
      id: '/jilles'
      path: '/jilles'
      fullPath: '/jilles'
      preLoaderRoute: typeof JillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/': {
      id: '/wiki/$slug/'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug/'
      preLoaderRoute: typeof WikiSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/history': {
      id: '/wiki/$slug/history'
      path: '/wiki/$slug/history'
      fullPath: '/wiki/$slug/history'
      preLoaderRoute: typeof WikiSlugHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug/edit': {
      id: '/wiki/$slug/edit'
      path: '/wiki/$slug/edit'
      fullPath: '/wiki/$slug/edit'
      preLoaderRoute: typeof WikiSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JillesRoute: JillesRoute,
  NewRoute: NewRoute,
  WikiSlugEditRoute: WikiSlugEditRoute,
  WikiSlugHistoryRoute: WikiSlugHistoryRoute,
  WikiSlugIndexRoute: WikiSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
