/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugIndexRouteImport } from './routes/posts.$slug.index'
import { Route as PostsSlugHistoryRouteImport } from './routes/posts.$slug.history'
import { Route as PostsSlugEditRouteImport } from './routes/posts.$slug.edit'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugIndexRoute = PostsSlugIndexRouteImport.update({
  id: '/posts/$slug/',
  path: '/posts/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugHistoryRoute = PostsSlugHistoryRouteImport.update({
  id: '/posts/$slug/history',
  path: '/posts/$slug/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugEditRoute = PostsSlugEditRouteImport.update({
  id: '/posts/$slug/edit',
  path: '/posts/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/posts/$slug/edit': typeof PostsSlugEditRoute
  '/posts/$slug/history': typeof PostsSlugHistoryRoute
  '/posts/$slug/': typeof PostsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/posts/$slug/edit': typeof PostsSlugEditRoute
  '/posts/$slug/history': typeof PostsSlugHistoryRoute
  '/posts/$slug': typeof PostsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/posts/$slug/edit': typeof PostsSlugEditRoute
  '/posts/$slug/history': typeof PostsSlugHistoryRoute
  '/posts/$slug/': typeof PostsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/new'
    | '/posts/$slug/edit'
    | '/posts/$slug/history'
    | '/posts/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/new'
    | '/posts/$slug/edit'
    | '/posts/$slug/history'
    | '/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/new'
    | '/posts/$slug/edit'
    | '/posts/$slug/history'
    | '/posts/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewRoute: typeof NewRoute
  PostsSlugEditRoute: typeof PostsSlugEditRoute
  PostsSlugHistoryRoute: typeof PostsSlugHistoryRoute
  PostsSlugIndexRoute: typeof PostsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug/': {
      id: '/posts/$slug/'
      path: '/posts/$slug'
      fullPath: '/posts/$slug/'
      preLoaderRoute: typeof PostsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug/history': {
      id: '/posts/$slug/history'
      path: '/posts/$slug/history'
      fullPath: '/posts/$slug/history'
      preLoaderRoute: typeof PostsSlugHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug/edit': {
      id: '/posts/$slug/edit'
      path: '/posts/$slug/edit'
      fullPath: '/posts/$slug/edit'
      preLoaderRoute: typeof PostsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewRoute: NewRoute,
  PostsSlugEditRoute: PostsSlugEditRoute,
  PostsSlugHistoryRoute: PostsSlugHistoryRoute,
  PostsSlugIndexRoute: PostsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
